"""Compares statistics of real encoder embeddings against embeddings
generated by a trained N-conditioned GNF checkpoint, to check whether
the flow's generated samples actually resemble the true embedding
distribution the (unchanged, jointly-trained-with-the-encoder) decoder
was calibrated on.

Motivation: training loss looking healthy and per-sample log-probs
looking sane at generation time only measure self-consistency with the
*learned* prior -- they don't guarantee generated samples actually
resemble real data. If the flow didn't fully learn to reproduce the
true embedding distribution, generated samples can drift systematically
in scale/location, and pred_adj -- calibrated on real embeddings in
run_gnn.py's Step 1 -- would then predict "not connected" almost
everywhere on generated ones, exactly the near-empty-graph symptom
observed in generate_graphs.py's output.

Read-only: restores the checkpoint but never saves anything back.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import pickle
import warnings

from absl import flags
import graph_nets as gn
import numpy as np
import tensorflow as tf

from conditional_prior import ConditionalPriorNetwork, sample_conditional_prior
from grevnet import NConditionedGNFBlock
from n_conditioning import NEmbedding
from utils import reset_sess, senders_receivers

warnings.filterwarnings("ignore")

flags.DEFINE_string('checkpoint', '', 'Trained GNF checkpoint to restore.')
flags.DEFINE_string(
    'embeddings_file', '',
    'Pickled (node_embeddings, n_node) file of REAL embeddings, e.g. '
    'results/ego_conditioned/seed_1/node_embeddings/embeddings_1_0.p')
flags.DEFINE_integer('node_embedding_dim', 14, 'Must match training.')
flags.DEFINE_integer('num_coupling_layers', 12, 'Must match training.')
flags.DEFINE_integer('latent_dim', 2048, 'Must match training.')
flags.DEFINE_integer('n_embed_dim', 32, 'Must match training.')
flags.DEFINE_bool('weight_sharing', False, 'Must match training.')
flags.DEFINE_integer('sample_size', 32,
                     'Must match --sample_size used at training time '
                     '(fixes sample_n_node_placeholder\'s static shape).')
flags.DEFINE_integer('num_samples_to_compare', 512,
                     'How many real / generated node embeddings to '
                     'compare (generation happens in batches of '
                     'sample_size, so the actual count may run slightly '
                     'over this).')
FLAGS = tf.app.flags.FLAGS


def transform_example(n_node):
    globals_ = tf.zeros_like(n_node)
    senders, receivers = senders_receivers(n_node)
    senders.set_shape([None])
    receivers.set_shape([None])
    n_edge = tf.square(n_node)
    edges = tf.zeros_like(senders)
    return edges, globals_, receivers, senders, n_edge


# ============================================================
# Load REAL embeddings (no TF needed for this part).
# ============================================================
with open(FLAGS.embeddings_file, 'rb') as f:
    real_node_embeddings, real_n_node = pickle.load(f)
real_node_embeddings = np.array(real_node_embeddings)
real_n_node_list = list(real_n_node)
print("Loaded {} real node embeddings, dim {}, from {} graphs".format(
    real_node_embeddings.shape[0], real_node_embeddings.shape[1],
    len(real_n_node_list)))

# ============================================================
# Rebuild the model (same construction order as training, so
# variable names line up with the checkpoint), and wire up the
# exact same generation path generate_graphs.py uses.
# ============================================================
half_dim = FLAGS.node_embedding_dim // 2

n_node_placeholder = tf.placeholder(tf.int32, shape=[FLAGS.sample_size],
                                    name='n_node_placeholder')
edges, globals_, receivers, senders, n_edge = transform_example(
    n_node_placeholder)
dummy_nodes = tf.zeros(
    [tf.reduce_sum(n_node_placeholder), FLAGS.node_embedding_dim])
graph_phs = gn.graphs.GraphsTuple(nodes=dummy_nodes,
                                  edges=edges,
                                  globals=globals_,
                                  receivers=receivers,
                                  senders=senders,
                                  n_node=n_node_placeholder,
                                  n_edge=n_edge)

grevnet = NConditionedGNFBlock(
    num_timesteps=FLAGS.num_coupling_layers,
    node_embedding_dim=half_dim,
    hidden_dim=FLAGS.latent_dim,
    n_embed_dim=FLAGS.n_embed_dim,
    weight_sharing=FLAGS.weight_sharing,
    use_batch_norm=True)

prior_n_embedding_mod = NEmbedding(FLAGS.n_embed_dim)
prior_net = ConditionalPriorNetwork(FLAGS.node_embedding_dim)

# Forces every submodule's variables to be created in the same
# order/names as training, so the Saver below finds matches.
_ = grevnet(graph_phs, inverse=True)

n_embedding = prior_n_embedding_mod(graph_phs)
mu, sigma = prior_net(n_embedding)
sample = sample_conditional_prior(n_node_placeholder, mu, sigma)
sample_graph_phs = graph_phs.replace(nodes=sample)
# Same tensor generate_graphs.py's sample_pred_adj is decoded from.
generated_nodes = grevnet(sample_graph_phs, inverse=False).nodes

sess = reset_sess()
saver = tf.train.Saver()
print("Restoring from {}".format(FLAGS.checkpoint))
saver.restore(sess, FLAGS.checkpoint)

# ============================================================
# Generate samples, conditioning N on real graphs' own node
# counts (same as generate_graphs.py does), until we have enough.
# ============================================================
generated_chunks = []
total = 0
n_node_ind = 0
while total < FLAGS.num_samples_to_compare:
    batch_n = [
        real_n_node_list[(n_node_ind + i) % len(real_n_node_list)]
        for i in range(FLAGS.sample_size)
    ]
    n_node_ind += FLAGS.sample_size
    vals = sess.run(generated_nodes,
                    feed_dict={n_node_placeholder: batch_n})
    generated_chunks.append(vals)
    total += vals.shape[0]

generated_embeddings = np.concatenate(generated_chunks, axis=0)

rng = np.random.RandomState(0)
real_sample_size = min(FLAGS.num_samples_to_compare,
                       real_node_embeddings.shape[0])
real_sample = real_node_embeddings[rng.choice(
    real_node_embeddings.shape[0], size=real_sample_size, replace=False)]


def report(name, arr):
    print("\n{} (n={}, dim={}):".format(name, arr.shape[0], arr.shape[1]))
    print("  per-dim mean (first 5 dims): {}".format(
        np.array2string(np.mean(arr, axis=0)[:5], precision=4)))
    print("  per-dim std  (first 5 dims): {}".format(
        np.array2string(np.std(arr, axis=0)[:5], precision=4)))
    print("  mean |value| over all dims: {:.4f}".format(
        np.mean(np.abs(arr))))
    print("  std of values over all dims: {:.4f}".format(np.std(arr)))
    print("  mean L2 norm per sample:    {:.4f}".format(
        np.mean(np.linalg.norm(arr, axis=1))))
    return np.mean(np.linalg.norm(arr, axis=1))


print("=" * 70)
real_norm = report("REAL embeddings", real_sample)
gen_norm = report("GENERATED embeddings", generated_embeddings)
print("\n--> mean L2 norm ratio (generated / real): {:.4f}".format(
    gen_norm / real_norm))
print("    (close to 1.0 = similar scale; far from 1.0 = scale mismatch,")
print("     which would explain the decoder failing on generated samples)")
print("=" * 70)
